### ISSUE TITLE
หน้าปกเกม

### ISSUE THREAD

**Issue by faiinrd** [KaiZer003/Scratch_Project_20#12]

**Comment by xtxme** [comment]
![เครดิต 64](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/ee4d6cd3-f59c-421f-8393-8afbe9856b7f)

**Comment by xtxme** [comment]
![เริ่ม 64](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/0a05208d-83fa-43f4-9d88-62f03633587e)

**Comment by xtxme** [comment]
![เริ่มใหม่ 64](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/a26e4370-b0a1-4049-8b11-1af815c68d02)

**Comment by faiinrd** [comment]
![ชื่อเกม](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/0d549400-cc7e-4a24-83d7-d172b3c802be)

**Comment by faiinrd** [comment]
![ปกแยก](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/ad62d7af-d186-4c0a-afb7-c13813df936f)

**Comment by xtxme** [comment]
![ปก Credit](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/868a0211-0daf-4650-9fe7-1064a9460287)
