### ISSUE TITLE
ด่าน cal

### ISSUE THREAD

**Issue by faiinrd** [KaiZer003/Scratch_Project_20#13]

**Comment by faiinrd** [comment]
![ชั้นวางหนังสือ](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/7aa3c130-9892-4dd5-a183-f73eb10dfaa8)

**Comment by faiinrd** [comment]
![นาฬิกา](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/b9940eae-80c4-4914-a648-45fb6100692c)

**Comment by xtxme** [comment]
![Map1 Floor1 Blocks](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/e9ec416e-730d-4e3d-b1f8-289db9199121)

**Comment by xtxme** [comment]
![Map1 Floor2 Blocks](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/0ff47a82-bd0c-4aef-8826-79ca26950676)

**Comment by faiinrd** [comment]
![ผนังแคล](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/a3489efd-1847-4b5d-bf28-3876eeda320e)

**Comment by faiinrd** [comment]
![ผนังด่านแคล](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/3fa030df-70dc-4aa4-92bf-b8215ee0293c)
