### ISSUE TITLE
ด่าน phy

### ISSUE THREAD

**Issue by faiinrd** [KaiZer003/Scratch_Project_20#14]

**Comment by faiinrd** [comment]
![374967475_551551617097326_9066448794134379461_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/0cf91749-56b4-4da3-80c0-d6e95737eb2b)

**Comment by faiinrd** [comment]
![373474440_269567499261746_5745063356961918776_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/eda0282d-d445-42a8-ac36-1ca9527e9a44)

**Comment by faiinrd** [comment]
![377124878_258108893810444_6121108717577220265_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/9bc83ba7-6a7b-4eed-96b5-e98389c06dbb)
![373460367_2389075964627399_5970554978467545240_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/88eca17a-51f8-485a-b118-b314c0f716e8)

**Comment by faiinrd** [comment]
![373459239_695529775938962_833511534877447812_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/99a80fbd-cf6f-49dc-bcc1-7324879030fa)

**Comment by faiinrd** [comment]
![373462030_1325555935048411_6654221013806867143_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/7266a2da-5092-42f7-b38b-fe518def77f7)

**Comment by xtxme** [comment]
![373463836_1409470623117674_4778274623683817328_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/acd73d8b-91d6-4cf5-9d25-956c490cd9aa)

**Comment by faiinrd** [comment]
![บล็อกด่านฟิ แก้](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/f5691b06-c7de-44ff-bc8e-4132e365c096)

**Comment by faiinrd** [comment]
![ผนังฟิ](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/e15cbbb7-0ece-467a-b02c-4a94558e1e1c)
