### ISSUE TITLE
items + trap

### ISSUE THREAD

**Issue by faiinrd** [KaiZer003/Scratch_Project_20#18]

**Comment by faiinrd** [comment]
![เครื่องดื่มชูกำลัง](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/9f1dde87-8745-4a72-a796-efcc6be40dc1)
![เครื่องดื่มชูกำลัง 64](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/a03f5257-e9c9-4c29-a627-2de00c10054f)

**Comment by faiinrd** [comment]
![เบียร์](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/b8bde125-fa99-471e-94cc-7d30ff2b13e9)

**Comment by faiinrd** [comment]
![ระเบิด](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/752f8a50-db6a-4c69-a4a9-4069cdec8923)

**Comment by xtxme** [comment]
![กับดักปลายแหลม 64](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/e9d63de2-fcdd-41af-812f-b696faaa1b78)

**Comment by xtxme** [comment]
![portal door ปิด 64](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/0201d19a-aefc-4e69-a4c1-fdc7a26a9714)

**Comment by faiinrd** [comment]
![375760721_1454777258643425_6967197950912790734_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/6e710245-b56f-4a53-a800-2e431d6fe53b)

**Comment by xtxme** [comment]
![brain](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/449ac91b-88dd-4c46-9e1a-5867a9adaa30)

**Comment by faiinrd** [comment]
![ปากกา](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/501ca5d3-36e8-4bc4-8203-6f959551592c)

**Comment by faiinrd** [comment]
![เลื่อย](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/b3469091-05a3-4095-b6f3-8f8ec0ae9f58)
