### ISSUE TITLE
ตัวละคร 

### ISSUE THREAD

**Issue by faiinrd** [KaiZer003/Scratch_Project_20#19]

**Comment by xtxme** [comment]
![ตัวละคร2](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/17ebdec2-6bf8-4e14-9936-0a1b125b5d24)

**Comment by xtxme** [comment]
![F 64](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/48339d0a-cba6-4708-8789-7ddf9241b262)

**Comment by faiinrd** [comment]
![375037033_6809408265747076_6884020291635129966_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/e66e41fc-f406-479a-9900-dea448ef8e97)
![375889131_199963056274793_7394346047306048335_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/ea05da3f-ce16-4588-8c5b-edaa7d699bbd)
![368581287_1704569753375660_7915892783857898569_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/79ebd812-e330-4ac7-af02-04822cbf3f4c)

**Comment by faiinrd** [comment]
![374811994_334794572329878_3725705004055137937_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/c1ae7497-a1b3-4d11-a0cb-722e0a0a8cbf)

**Comment by faiinrd** [comment]
![368462630_238387718743144_3950535283688895034_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/d6971a59-2967-4700-bef4-e514b4e02baa)
![374582344_3227196014240428_2721744612518240018_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/617ef936-ff70-4586-bb09-eae519b8888c)

**Comment by faiinrd** [comment]
![368720568_334794565663212_5424369377979614893_n](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/4e32e9f0-19d5-4d8c-9ba9-9dbc27836623)

**Comment by faiinrd** [comment]
![boss ข้างหน้า มีหัว](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/505ec54a-f733-4f02-9c23-6fb23837d1fe)
![boss ข้างขวา](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/81a57dc9-a4fc-4882-865e-79f70385bf9e)
![boss ข้างซ้าย มีหัว](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/a5457100-a33c-4916-8db7-4c7295f238bd)

**Comment by faiinrd** [comment]
![ตลค](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/9c71d3fc-376b-4087-aee5-6ab80570429d)
![ตลค2](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/8ef708a4-a466-4913-9d36-f13c267a570c)
![ตลค3](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/ed42feb8-a56f-4924-8efb-1f4c445aeb77)
