### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by faiinrd** [KaiZer003/Scratch_Project_20#23]

**Comment by xtxme** [comment]
![เริ่ม 64](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/f0f00cab-09a1-453c-bbcc-d2e71fd77f20)

**Comment by xtxme** [comment]
![เครดิต 64](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/885083aa-bbe8-4ac4-b901-67dd1ca1425a)

**Comment by xtxme** [comment]
![Back แก้](https://github.com/KaiZer003/Scratch_Project_20/assets/141804351/01d566bd-0aac-451d-b7c3-c6f98f35166e)

**Comment by faiinrd** [comment]
![re](https://github.com/KaiZer003/Scratch_Project_20/assets/141803648/489f84d5-35c7-4918-b635-699f37d69cde)
