### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jow9wachirawit** [KaiZer003/Scratch_Project_20#26]

**Comment by jow9wachirawit** [comment]
---------------------BUG----------------------
- [x] ตัวชนพื้นเเล้วพุ่งขึ้น
- [x] ตายเเล้วเกมไม่หยุด
- [x] ตีมอนไม่ตาย
- [x] บอสไม่เกิด
- [x] ด่านบอสเดินกลับเเล้วบัค

**Comment by KaiZer003** [comment]
> ---------------------BUG----------------------
> 
> * [ ]  ตัวชนพื้นเเล้วพุ่งขึ้น
> * [ ]  ตายเเล้วเกมไม่หยุด
> * [ ]  ตีมอนไม่ตาย
> * [ ]  บอสไม่เกิด
> * [ ]  ด่านบอสเดินกลับเเล้วบัค

**Comment by jow9wachirawit** [comment]
- [x] เลือดบอสไม่ขึ้น
- [x] ประตูไม่ตรวจคะเเนน
- [x] F ไม่จับตัวละคร
