### ISSUE TITLE
Sound Design

### ISSUE THREAD

**Issue by jow9wachirawit** [KaiZer003/Scratch_Project_20#6]
- [x] เลือกเครื่องมือสร้างเสียงประกอบ
- [x] ออกเเบบเสียงประกอบที่เหมาะสม

**Comment by faiinrd** [comment]
เสียงกดปุ่ม
[กดปุ่ม.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12523690/default.zip)

**Comment by faiinrd** [comment]
เสียงกระโดด
[AnyConv.com__กระโดด.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12523675/AnyConv.com__.zip)

**Comment by faiinrd** [comment]
เสียงเก็บ items
[เก็บไอเทม.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12523701/default.zip)

**Comment by faiinrd** [comment]
เสียงเดิน+วิ่ง
[เดิน+วิ่ง.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12523703/%2B.zip)

**Comment by faiinrd** [comment]
เสียงโดนทำ damage
[โดนทำดาเมจ.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12523705/default.zip)

**Comment by faiinrd** [comment]
เสียงยิง
[ยิง.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12523707/default.zip)

**Comment by faiinrd** [comment]
เสียงโยนเลื่อย
[โยนเลื่อย.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12523710/default.zip)

**Comment by faiinrd** [comment]
เสียงเกมแพ้
[แพ้.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12523715/default.zip)

**Comment by faiinrd** [comment]
เสียงเกมชนะ
[ชนะ.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12523716/default.zip)

**Comment by faiinrd** [comment]
เสียงกระโดด
[กระโดด.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12523727/default.zip)

**Comment by faiinrd** [comment]
เสียงตีมอน
[ตีมอน.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12565217/default.zip)

**Comment by faiinrd** [comment]
[AnyConv.com__ด่านแคล.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12565297/AnyConv.com__.zip)

**Comment by faiinrd** [comment]
[ด่านแคล.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12565301/default.zip)

**Comment by faiinrd** [comment]
[ด่านฟิ.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12565306/default.zip)

**Comment by faiinrd** [comment]
[ด่านบอส.zip](https://github.com/KaiZer003/Scratch_Project_20/files/12565309/default.zip)
